language: node
rvm:
  - 10.15.3
env: node

services:
  - docker
script:
  - docker build -t sirrius/demo:sails-api .

after _success:
  - if [["$TRAVIS_BRANCH" == "master" ]]; then
       docker login -u "${DOCKER_USERNAME}" -p "DOCKER_PASSWORD}";
       docker push sirrius/demo:sails-api ;
    fi
